---         
apiVersion: v1
kind: Namespace
metadata:
  name: webapp
  labels:
    istio-injection:
      enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-pod
  namespace: webapp
  labels:
    app: web-app
    version: v1
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        version: v1
    spec: 
      containers:
      - name: web
        image: wonezwan1/olauwu:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  namespace: webapp
spec:   
  selector:
    app: web-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
